# Generated by Django 4.2.3 on 2023-07-15 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_has_like'),
    ]

    operations = [

    ]
