# Generated by Django 4.2.3 on 2023-07-15 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_likeuser_alter_user_has_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='has_like',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
