# Generated by Django 4.2.3 on 2023-07-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_has_like_delete_likeuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='has_like',
            new_name='liked',
        ),
    ]
