# Generated by Django 4.2.3 on 2023-07-16 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_has_like_user_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
            preserve_default=False,
        ),
    ]
